services:
  # PostgreSQL database for Temporal
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - temporal-network

  # Temporal server with auto-setup
  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
      - "8080:8080"
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
    depends_on:
      - postgres
    networks:
      - temporal-network

  # Go application container
  temporal-go-examples:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    working_dir: /app
    environment:
      - TEMPORAL_HOSTPORT=temporal:7233
    depends_on:
      - temporal
    networks:
      - temporal-network
    command: ["bash", "-c", "sleep 30 && echo '🎯 Temporal Go Examples Development Container' && echo '' && echo 'Available commands:' && echo '  ./run-example.sh <example> <worker|client>' && echo '  ./check-temporal.sh' && echo '  bash  # Interactive shell' && echo '' && echo 'Temporal server should be at temporal:7233' && echo 'Web UI should be at http://localhost:8080' && echo '' && exec bash"]
    stdin_open: true
    tty: true

volumes:
  postgres-data:
  go-modules:

networks:
  temporal-network:
    driver: bridge
